#!/bin/python3

import argparse

def add_numbers (a,b):
	return  a + b


if __name__ == "__main__":
	parser = argparse.ArgumentParser(description="Add two numbers")
	parser.add_argument("num1", type=float, help="first number")
	parser.add_argument("num2", type=float, help="second number")

	args = parser.parse_args()

	result = add_numbers(args.num1,args.num2)
	print(f"The sum is: {result}")

